### PR TITLE
refactor: navbar

### PR DESCRIPTION
**Pull request by ivan-ngchakming**
# Pull request

## Description

Refactored NavBar:
- removed nested structure of components (`./components/navbar/components/searchbar/searchbar.tsx` is just confusing and unnecessary amount of subfolders, @nmp14 see if you agree or we should discuss before merging the pr)
- used styled component instead of external css for consistency

Updated navbar styles
- changed background color of navbar to be consistent with logo
- use material icons instead of weird svg sheet from amazon

image

continuation of #73 

## Type of Change

- [ ] Refactor (non-breaking change which improves code performance or readability)
- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change that adds functionality)
- [ ] Documentation (changes to docs and not code)
- [ ] Breaking Change (Fix or change that would cause existing functionality to not work as expected)
- [ ] Test

## How it was tested

Enter description of testing

- [ ] Unit Test
- [ ] Manual / Postman(if backend)
- [ ] Integration

## Affirmations

- [ ] I follow coding guidelines (TBD)
- [ ] I have self-reviewed my code
- [ ] I have run eslint and fixes issues (Mostly works but needs more rules and a fix)
- [ ] I have commented code when necessary or difficult
- [ ] I have made changes to docs where required
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing tests pass

### CODE REVIEW

**Comment by nmp14** [comment]
@ivan-ngchakming   In reference to the file structure, it depends on if you plan to use this search bar anywhere outside of the navbar. Nesting components in other components creates a structured way of finding things in larger projects where new people may come in and have no clue what's going on. If the search bar component is ever reused somewhere else it's fine to have as a high level component, but it adds more organization to contain it in the Navbar component if it will never be used outside of it. It is of course a preference thing. If yall dislike it, we don't have to do it that way. But just imagine if yall actually develop this project and the size gets somewhat large (amazon is not actually that simple of a site if you start getting into all of it). The better you break down your components, aka resulting in simpler files but more components, will create a super large components folder if everything is there in a monolithic project such as this (monoliths mean the entirety of the FE is contained in one project. And the BE monoliths are one server that contains every service.).  Simply put, it's one of several design options aimed at starting a project to have better code maintainability and readability as it grows in size.

**Comment by ivan-ngchakming** [comment]
Agreed, having nested structure would have the added benefit of easy navigation between components. 

Currently the project is still pretty small and the search bar is a somewhat generic component, perhaps we can keep this flatter structure and revisit if we want to introduce a more complex one should the need arise?

**Comment by fidel-bello** [comment]
@ivan-ngchakming  lets keep the project simple for now and.. once we start adding more components we can make it nested.

**Comment by fidel-bello** [comment]
hi @ivan-ngchakming  did you mean to change the color of the nav to yellow and the other pull request to blue?? I like the yellow

**Review by fidel-bello — COMMENTED** [review]
hi actually like the nested components, I feel this app will get pretty big, can you please refactor back to nested and also like that color navbar color.. we will keep the styled components instead outside css  if media queries arent an issue

**Comment by ivan-ngchakming** [comment]
> hi @ivan-ngchakming did you mean to change the color of the nav to yellow and the other pull request to blue?? I like the yellow

The other PR has a blue nav bar because this PR responsible for changing it to blue is not merged yet

> we will keep the styled components instead outside css if media queries arent an issue
media query is not an issue, its just css in js, plus mui has a media query hook

**Review by fidel-bello — APPROVED** [review]

**Pull request merged**
