### PR TITLE
added some fixes

### PR DESCRIPTION
**Pull request by fidel-bello**
# Pull request

## Description

[//]: # (Summary of changes. List any dependency changes required for this change)
Fixes # (issue)

(Enter your description here)

## Type of Change

- [x] Refactor (non-breaking change which improves code performance or readability)
- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change that adds functionality)
- [ ] Documentation (changes to docs and not code)
- [x] Breaking Change (Fix or change that would cause existing functionality to not work as expected)
- [ ] Test

## How it was tested

Enter description of testing

- [ ] Unit Test
- [ ] Manual / Postman(if backend)
- [ ] Integration

## Affirmations

- [ ] I follow coding guidelines (TBD)
- [ ] I have self-reviewed my code
- [x] I have run eslint and fixes issues (Mostly works but needs more rules and a fix)
- [ ] I have commented code when necessary or difficult
- [ ] I have made changes to docs where required
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing tests pass

### CODE REVIEW

**Comment by ivan-ngchakming** [comment]
Why use named export instead of default export?

**Comment by fidel-bello** [comment]
the way it was left it caused bugs, plus I mentioned that I wanted to keep the app like it was set up for practice. The benefit is a great way to organize this app. once we start adding more component, we will be more organized

**Comment by ivan-ngchakming** [comment]
Okay, I will stick to named export for everything from now on then. 

May i ask what bug was it causing? I didnt encounter it before, maybe its my mistake during development and I'd like to learn from it.

**Comment by fidel-bello** [comment]
> Okay, I will stick to named export for everything from now on then. (Personally i prefer default export for the components)
> 
> May i ask what bug was it causing? I didnt encounter it before, maybe its my mistake during development and I'd like to learn from it.

It was something about export defaults wasn't the proper way to exporting to the index. looks like it was just some wrong syntax from your last push.. I'm not entirely sure but I just went back to how it was originally set up and it was fixed.

**Comment by ivan-ngchakming** [comment]
> It was something about export defaults wasn't the proper way to exporting to the index. looks like it was just some wrong syntax from your last push..

I cannot seem to find any errors or issues at the `main` branch? Can you be more specific?

**Comment by fidel-bello** [comment]
I honestly don't remember what the actually error react was giving. But it had to do with the navbar.tsx and searchbar.tsx. Whenever I pulled your pr, I npm start, and it threw error with the component path. I honestly didn't pay too much attention as I knew that I was going to just revert back to the original setup in which was not much different from you last pr. But it was fixed. I should've taken a screenshot a post it as issue since we are learning here. Next time!

**Comment by nmp14** [comment]
In regards to default vs named exports. It doesn't really matter that much, it's mostly subjective. The few difference involve only being able to have 1 default import per file, and how to import them. It's common to use default exports for anything that is like an entry point to project or something. Think npm packes like express or mongoose, etc. We call express whatever we want when we import it. For things like React components or classes, that are used internally for the project, again it's subjective, but there are some considerations. A main one is that named exports can cause higher consistency vs default exports. A default export can be named anything on import so dev1 can import a component called ContactCard as "import Card from 'path'" (Card isn't very specific and can cause issues with name conflicts or searching files), dev2 can import it as "import ContactCard from 'path'", and even worse, dev3 can typo it as 'import CoontactCar' from 'path'".  This can't happen in named exports as it wont be found (you can technically alias, but why would you alias for no reason? If you dont have a reason in a stricter project they'll probably question the alias.) And so on but either works generally for a single export.

**Comment by nmp14** [comment]
Anyways I fixed one path you, @fidel-bello, had in app.tsx that imported directly from Navbar/Navbar instead of the index file and pushed it. Looks good otherwise. @ivan-ngchakming in terms of the version on main, I also don't have any errors, but it could use minor refactoring anyways. Whether you do nested components or not, things like the SearchBar component shouldn't be in the root of a folder called Navbar. It comes off as disorganized to some people. If not nesting, it would just be its own component file or folder in the root of components. If nesting, should have a folder or something like components to make it clear for other readers that it's a contained component.

**Review by nmp14 — APPROVED** [review]

**Comment by fidel-bello** [comment]
ok nice, thanks for the explanation! alot of learning in this project!

**Pull request merged**
